---

- name: distcc | packages
  tags:
    - package
  package:
    name: distcc-pump
  notify: restart distcc

- name: distcc | config
  tags:
    - config
  template:
    src: distcc.j2
    dest: /etc/default/distcc
  notify: restart distcc

- name: distcc | service
  tags:
    - service
  service:
    name: distcc
    state: "{{ distcc_listen | ternary('started', 'stopped') }}"
    enabled: "{{ distcc_listen | ternary('yes', 'no') }}"
